"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import type { z } from "zod";
import type { AdminTransactionsResult, AdminTransactionDetail, transactionFilters } from "@/lib/admin-workspace";
import styles from "../admin.module.css";
const money = (amount: string, currency = "NGN") => new Intl.NumberFormat("en-NG",{style:"currency",currency}).format(Number(amount));
const date = (value: string) => new Date(value).toLocaleString("en-GB",{timeZone:"Africa/Lagos"});
export default function AdminTransactionsClient({ initial, filters, invalidFilters }: { initial: AdminTransactionsResult; filters: z.infer<typeof transactionFilters>; invalidFilters: boolean }) {
  const [detail, setDetail] = useState<AdminTransactionDetail | null>(null), [busy, setBusy] = useState(false), [error,setError] = useState(invalidFilters ? "Some filters were invalid. Showing all transactions." : "");
  const detailRef = useRef<HTMLElement>(null);
  function href(page: number) { return `/admin/transactions?${new URLSearchParams({ q: filters.q, status: filters.status, funds: filters.funds, ...(filters.from ? {from:filters.from} : {}), ...(filters.to ? {to:filters.to} : {}), page: String(page) })}`; }
  async function inspect(id: string) {
    setBusy(true); setError("");
    try {
      const response = await fetch(`/api/admin/transactions/${encodeURIComponent(id)}`,{cache:"no-store"}), body = await response.json();
      if (!response.ok) throw new Error(body.message || "We couldn’t load this transaction.");
      setDetail(body); requestAnimationFrame(() => { detailRef.current?.scrollIntoView({ block:"start",behavior:"smooth" }); detailRef.current?.focus({preventScroll:true}); });
    } catch (failure) { setError(failure instanceof Error ? failure.message : "We couldn’t load this transaction."); }
    finally { setBusy(false); }
  }
  return <main className={styles.content}><p className="eyebrow">Financial oversight</p><h1>Transactions</h1><p className={styles.intro}>Search every recorded payment, including failed and cancelled attempts. Dates use Nigeria time. Amounts represent recorded payment orders; pending and failed amounts are not received funds.</p>
    <form action="/admin/transactions" className={styles.filters}><label>Find a transaction<input name="q" type="search" defaultValue={filters.q} maxLength={120} placeholder="Reference, name, email or transaction ID" /></label><label>Payment status<select name="status" defaultValue={filters.status}><option value="all">All statuses</option>{["created","pending","paid","failed","cancelled","refunded"].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>Funds status<select name="funds" defaultValue={filters.funds}><option value="all">All funds</option>{["not_received","held","releasable","released","refunded","disputed"].map(value=><option key={value} value={value}>{value.replace("_"," ")}</option>)}</select></label><label>From<input type="date" name="from" defaultValue={filters.from} /></label><label>To<input type="date" name="to" defaultValue={filters.to} /></label><button>Search transactions</button><Link href="/admin/transactions">Reset</Link></form>
    {error && <p className={styles.error} role="alert">{error}</p>}
    <div className={styles.pagination}><span>{initial.total} matching transactions</span><strong>Total order amount: {money(initial.amount)}</strong></div>
    <div className={styles.tableWrap}><table className={styles.table}><caption>Payment records · page {initial.page}</caption><thead><tr><th scope="col">Reference and service</th><th scope="col">Customer and vendor</th><th scope="col">Amount</th><th scope="col">Status</th><th scope="col">Created</th><th scope="col">Details</th></tr></thead><tbody>{initial.transactions.map(transaction=><tr key={transaction.id}><td><strong>{transaction.reference}</strong><small>{transaction.service}</small><small>{transaction.provider} · {transaction.purpose}</small></td><td><strong>{transaction.customer}</strong><small>{transaction.customerEmail}</small><small>Vendor: {transaction.vendor}</small>{(transaction.customerFlagged || transaction.vendorFlagged) && <span className={`${styles.badge} ${styles.warning}`}>Flagged account involved</span>}</td><td><strong>{money(transaction.amount,transaction.currency)}</strong></td><td><span className={styles.badge}>{transaction.status}</span><small>{transaction.fundsStatus.replace("_"," ")}</small></td><td>{date(transaction.createdAt)}</td><td><div className={styles.actions}><button disabled={busy} aria-label={`Inspect transaction ${transaction.reference}`} aria-expanded={detail?.transaction.id === transaction.id} onClick={() => void inspect(transaction.id)}>Inspect</button></div></td></tr>)}</tbody></table>{!initial.transactions.length && <p style={{padding:18}}>No transactions match these filters.</p>}</div>
    <nav className={styles.pagination} aria-label="Transaction pages">{filters.page > 1 ? <Link href={href(filters.page-1)}>Previous page</Link> : <span /> }<span>Page {filters.page} · {initial.total} transactions</span>{filters.page*initial.pageSize < initial.total && <Link href={href(filters.page+1)}>Next page</Link>}</nav>
    {detail && <section ref={detailRef} tabIndex={-1} className={`${styles.panel} ${styles.detail}`} aria-labelledby="transaction-heading"><div className={styles.pagination}><h2 id="transaction-heading">Transaction details</h2><div className={styles.actions}><button onClick={() => setDetail(null)}>Close details</button></div></div>
      <dl className={styles.details}><div><dt>Reference</dt><dd>{detail.transaction.reference}</dd></div><div><dt>Payment / funds</dt><dd>{detail.transaction.status} / {detail.transaction.fundsStatus.replace("_"," ")}</dd></div><div><dt>Order amount</dt><dd>{money(detail.transaction.amount,detail.transaction.currency)}</dd></div><div><dt>Booking</dt><dd>{detail.transaction.bookingId}</dd></div><div><dt>Customer</dt><dd>{detail.transaction.customer} · {detail.transaction.customerEmail}{detail.transaction.customerFlagged && " · Flagged"}</dd></div><div><dt>Vendor</dt><dd>{detail.transaction.vendor} · {detail.transaction.vendorEmail}{detail.transaction.vendorFlagged && " · Flagged"}</dd></div><div><dt>Created</dt><dd>{date(detail.transaction.createdAt)}</dd></div><div><dt>Paid at</dt><dd>{detail.transaction.paidAt ? date(detail.transaction.paidAt) : "Not recorded"}</dd></div></dl>
      <h3>Disputes and refunds</h3>{!detail.cases.length && <p>No cases recorded.</p>}<ul className={styles.activity}>{detail.cases.map(item=><li key={item.id}><strong>{item.type} · {item.status}</strong><p>{item.reason}</p><time dateTime={item.createdAt}>{date(item.createdAt)}</time></li>)}</ul>
      <h3>Payout records</h3>{!detail.payouts.length && <p>No payouts recorded.</p>}<ul className={styles.activity}>{detail.payouts.map(item=><li key={item.id}>{money(item.amount)} · {item.status}<p>{date(item.createdAt)}</p></li>)}</ul>
      <h3>Payment events</h3>{!detail.events.length && <p>No events recorded.</p>}<ul className={styles.activity}>{detail.events.map(item=><li key={item.id}><strong>{item.type.replace(/[._]/g," ")}</strong><p><time dateTime={item.createdAt}>{date(item.createdAt)}</time></p></li>)}</ul><p className={styles.muted}>Showing up to 100 recent events, 50 cases and 50 payouts. Use Finance controls for reconciliation and existing refund workflows.</p><Link className={styles.button} href="/admin/payments">Open finance controls</Link>
    </section>}
  </main>;
}
