import type { PaymentReceiptData } from "@/lib/payments";

function ascii(value: string) {
  return value
    .replace(/[–—]/g, "-")
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, "");
}

function esc(value: string) {
  return ascii(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function money(value: number) {
  return "NGN " + new Intl.NumberFormat("en-NG", { maximumFractionDigits: 0 }).format(value);
}

function dateTime(value: string) {
  return new Intl.DateTimeFormat("en-NG", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}

function purposeLabel(value: PaymentReceiptData["purpose"]) {
  if (value === "deposit") return "Deposit payment";
  if (value === "balance") return "Balance payment";
  return "Full payment";
}

function wrap(value: string, max = 72) {
  const words = ascii(value).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const next = current ? current + " " + word : word;
    if (next.length > max && current) {
      lines.push(current);
      current = word;
    } else current = next;
  }
  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

export function buildPaymentReceiptPdf(receipt: PaymentReceiptData) {
  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 54;
  const commands: string[] = [];
  let y = 786;

  const text = (value: string, x: number, size = 10, bold = false) => {
    commands.push(`BT /${bold ? "F2" : "F1"} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${esc(value)}) Tj ET`);
  };
  const rule = () => commands.push(`0.86 G 0.7 w ${margin} ${y} m ${pageWidth - margin} ${y} l S`);
  const wrapped = (value: string, x: number, size = 10, bold = false, max = 72, leading = 14) => {
    for (const line of wrap(value, max)) {
      text(line, x, size, bold);
      y -= leading;
    }
  };

  text("SMITTEN", margin, 18, true);
  text("PAYMENT RECEIPT", pageWidth - margin - 116, 9, true);
  y -= 34;
  rule();
  y -= 30;

  text("Payment confirmed", margin, 23, true);
  y -= 27;
  wrapped(`${purposeLabel(receipt.purpose)} for ${receipt.serviceSummary}`, margin, 11, false, 70, 15);
  y -= 6;

  text("AMOUNT PAID", margin, 8, true);
  y -= 18;
  text(money(receipt.amount), margin, 26, true);
  y -= 34;
  rule();
  y -= 24;

  const labelX = margin;
  const valueX = 215;
  const row = (label: string, value: string, wrapValue = false) => {
    text(label.toUpperCase(), labelX, 8, true);
    if (wrapValue) {
      const originalY = y;
      wrapped(value, valueX, 9, false, 46, 12);
      if (y === originalY) y -= 14;
    } else {
      text(value, valueX, 9);
      y -= 19;
    }
  };

  row("Customer", receipt.customerName);
  row("Vendor", receipt.vendorName);
  row("Service", receipt.serviceSummary, true);
  row("Payment type", purposeLabel(receipt.purpose));
  row("Paid", dateTime(receipt.paidAt));
  row("Smitten payment ID", receipt.paymentId);
  row("Paystack reference", receipt.providerReference);
  row("Booking ID", receipt.bookingId);
  y -= 4;
  rule();
  y -= 24;

  text("BOOKING PAYMENT SUMMARY", margin, 9, true);
  y -= 20;
  row("Booking total", money(receipt.bookingTotal));
  row("Paid after this payment", money(receipt.paidAfterThisPayment));
  row("Remaining balance", money(receipt.remainingAfterThisPayment));

  if (receipt.weddingDate || receipt.weddingLocation) {
    y -= 6;
    rule();
    y -= 23;
    text("BOOKING DETAILS", margin, 9, true);
    y -= 20;
    if (receipt.weddingDate) row("Wedding date", receipt.weddingDate);
    row("Location", receipt.weddingLocation, true);
  }

  y -= 10;
  rule();
  y -= 20;
  wrapped(
    receipt.status === "refunded"
      ? "This receipt records the original successful payment. Smitten currently records this transaction as refunded."
      : "This receipt confirms a payment verified by Smitten against Paystack. It is not a tax invoice from the vendor.",
    margin,
    8,
    false,
    88,
    12,
  );
  y -= 8;
  text("Generated by Smitten", margin, 8);
  text("Currency: NGN", pageWidth - margin - 78, 8);

  const stream = commands.join("\n");
  const objects: string[] = [];
  objects[1] = "<< /Type /Catalog /Pages 2 0 R >>";
  objects[2] = "<< /Type /Pages /Kids [5 0 R] /Count 1 >>";
  objects[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
  objects[4] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";
  objects[5] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents 6 0 R >>`;
  objects[6] = `<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`;

  let output = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (let id = 1; id < objects.length; id += 1) {
    offsets[id] = Buffer.byteLength(output, "utf8");
    output += `${id} 0 obj\n${objects[id]}\nendobj\n`;
  }
  const xref = Buffer.byteLength(output, "utf8");
  output += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let id = 1; id < objects.length; id += 1) {
    output += String(offsets[id]).padStart(10, "0") + " 00000 n \n";
  }
  output += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;

  return Buffer.from(output, "utf8");
}
