import type { QuoteView } from "@/lib/quotes";

function ascii(value: string) {
  return value
    .replace(/[–—]/g, "-")
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, "");
}

function esc(value: string) {
  return ascii(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function money(value: number) {
  return "NGN " + new Intl.NumberFormat("en-NG", { maximumFractionDigits: 0 }).format(value);
}

function wrap(value: string, max = 78) {
  const words = ascii(value).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const next = current ? current + " " + word : word;
    if (next.length > max && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

export function buildQuotePdf(quote: QuoteView) {
  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 54;
  const pages: string[][] = [[]];
  let page = pages[0];
  let y = 786;

  const text = (value: string, x: number, size = 10, bold = false) => {
    page.push(`BT /${bold ? "F2" : "F1"} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${esc(value)}) Tj ET`);
  };
  const rule = () => page.push(`0.86 G 0.7 w ${margin} ${y} m ${pageWidth - margin} ${y} l S`);
  const nextPage = () => {
    pages.push([]);
    page = pages[pages.length - 1];
    y = 786;
    text("SMITTEN", margin, 16, true);
    text("Wedding quote", pageWidth - margin - 88, 9, false);
    y -= 30;
    rule();
    y -= 24;
  };
  const ensure = (height: number) => { if (y - height < 72) nextPage(); };
  const lineText = (value: string, x: number, size = 10, bold = false, max = 78, leading = 14) => {
    for (const line of wrap(value, max)) {
      ensure(leading);
      text(line, x, size, bold);
      y -= leading;
    }
  };

  text("SMITTEN", margin, 18, true);
  text("WEDDING QUOTE", pageWidth - margin - 104, 9, true);
  y -= 34;
  rule();
  y -= 30;

  text(quote.title, margin, 23, true);
  y -= 26;
  text("Prepared by " + quote.vendorName, margin, 10);
  y -= 15;
  text("For " + quote.customerName, margin, 10);
  y -= 15;
  text("Quote #" + quote.id.slice(0, 8).toUpperCase() + "  |  Revision " + quote.revision, margin, 9);
  y -= 15;
  text("Status: " + quote.status.toUpperCase(), margin, 9, true);
  if (quote.validUntil) {
    y -= 15;
    text("Valid until: " + quote.validUntil, margin, 9);
  }
  y -= 26;
  rule();
  y -= 24;

  text("SERVICES", margin, 9, true);
  y -= 18;
  for (const item of quote.items) {
    ensure(58);
    text(item.title, margin, 11, true);
    text(money(item.lineTotal), pageWidth - margin - 110, 10, true);
    y -= 15;
    if (item.description) lineText(item.description, margin, 8, false, 72, 11);
    text("Qty " + item.quantity + " x " + money(item.unitPrice), margin, 8);
    y -= 18;
    rule();
    y -= 16;
  }

  ensure(120);
  text("Subtotal", pageWidth - margin - 210, 10);
  text(money(quote.subtotal), pageWidth - margin - 110, 10, true);
  y -= 17;
  if (quote.discountAmount > 0) {
    text("Discount", pageWidth - margin - 210, 10);
    text("-" + money(quote.discountAmount), pageWidth - margin - 110, 10, true);
    y -= 17;
  }
  if (quote.additionalFees > 0) {
    text("Additional fees", pageWidth - margin - 210, 10);
    text(money(quote.additionalFees), pageWidth - margin - 110, 10, true);
    y -= 17;
  }
  rule();
  y -= 19;
  text("TOTAL", pageWidth - margin - 210, 12, true);
  text(money(quote.total), pageWidth - margin - 110, 12, true);
  y -= 32;

  if (quote.notes) {
    ensure(80);
    text("NOTES", margin, 9, true);
    y -= 17;
    lineText(quote.notes, margin, 9, false, 82, 13);
    y -= 8;
  }

  ensure(54);
  rule();
  y -= 20;
  text("Generated by Smitten", margin, 8);
  text("Currency: NGN", pageWidth - margin - 78, 8);

  const objects: string[] = [];
  objects[1] = "<< /Type /Catalog /Pages 2 0 R >>";

  const pageRefs: string[] = [];
  const firstPageObjectId = 5;
  pages.forEach((_, index) => pageRefs.push(`${firstPageObjectId + index * 2} 0 R`));
  objects[2] = `<< /Type /Pages /Kids [${pageRefs.join(" ")}] /Count ${pages.length} >>`;
  objects[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
  objects[4] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";

  pages.forEach((commands, index) => {
    const pageId = firstPageObjectId + index * 2;
    const contentId = pageId + 1;
    const stream = commands.join("\n");
    objects[pageId] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentId} 0 R >>`;
    objects[contentId] = `<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`;
  });

  let output = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (let id = 1; id < objects.length; id += 1) {
    offsets[id] = Buffer.byteLength(output, "utf8");
    output += `${id} 0 obj\n${objects[id]}\nendobj\n`;
  }
  const xref = Buffer.byteLength(output, "utf8");
  output += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let id = 1; id < objects.length; id += 1) {
    output += String(offsets[id]).padStart(10, "0") + " 00000 n \n";
  }
  output += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(output, "utf8");
}
